
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/dbertsch/developmentEnvironments/clion-2023.3.4/bin/cmake/linux/aarch64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.28+rpt-rpi-2712 - aarch64
...
